config/routes.rb
Rails.application.routes.draw do

  get '/movies' => 'movies#index'
  get '/movies/:id' => 'movies#show', as: :movie
  get '/actors' => 'actors#index'
  get '/actors/:id' => 'actors#show', as: :actor

end

app/models/actor.rb
class Actor < ActiveRecord::Base
	has_many :parts 
	has_many :movies, through: :parts

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :parts 
	has_many :actors, through: :parts
end

app/models/part.rb
class Part < ActiveRecord::Base
	belongs_to :movie 
	belongs_to :actor
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
	def index
		@actors = Actor.all
	end
	
	def show
    @actor = Actor.find(params[:id])
    @movies = @actor.movies
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @actors = @movie.actors
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/actors/index.html.erb
<div class="main actor-index">
      <div class="container">
        <div class="row">
          <% @actors.each do |actor| %>
          <div class="actor col-xs-2">
            <%= image_tag actor.image %>
            <h3><%= actor.first_name + " " + actor.last_name %></h3>
            <%= link_to "Learn more", actor_path(actor) %>
          </div>
          <% end %>
        </div>
      </div>
</div>

app/views/actors/show.html.erb
<div class="main actor-show">
  <div class="container">
    
    <!-- Display an actor's info here -->
    <div class="actor">
      <%= image_tag @actor.image %>
      <div class="info">
        <h3 class="actor-name"><%= @actor.first_name + " " + @actor.last_name  %></h3>
        <p class="actor-bio"><%= @actor.bio %></p>
      </div>
    </div>

    <h2>Movies</h2>
    <% @movies.each do |movie| %>
    <div class="movies">
      <%= image_tag movie.image %>
      <h3 class="movie-title"><%= movie.title %></h3>
      <p class="movie-release-year"><%= movie.release_year %></p>
      <p class="movie-plot"><%= movie.plot %></p>
      <%= link_to "Read more", movie_path(movie) %>
    </div>
    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bolt Movie Database</title>
    <link href='http://fonts.googleapis.com/css?family=Oxygen:300,400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo.svg" height="40">
        <h1>Bolt Movie Database</h1>
      </div>
    </div>

    <%= yield %>

  </body>
</html>

app/views/movies/index.html.erb
<div class="hero">
  <div class="container">
    <h2>Interstellar</h2>
    <p>Former NASA pilot Cooper (Matthew McConaughey) and a team of researchers travel across the galaxy to find out which of three planets could be mankind's new home.</p>
    <a href="#">Read More</a>
  </div>
</div>

<div class="main">
  <div class="container">
  <h2>Popular Films</h2>
    <% @movies.each do |movie| %>
    <div class="movies">
      <%= image_tag movie.image %>
      <h3><%= movie.title %></h3>
      <p><%= movie.release_year %></p>
      <p><%= movie.plot %></p>
      <%= link_to "Learn more", movie_path(movie) %>
    </div>
    <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="main movie-show">
  <div class="container">
    
    <div class="movie">
      <!-- Display the movie's info here -->
      <div class="info">
        <%= image_tag @movie.image %>
        <h3 class="movie-title"><%= @movie.title %></h3>
        <p class="movie-release-year"><%= @movie.release_year %></p>
        <p class="movie-plot"><%= @movie.plot %></p>
      </div>
    </div>

    <h2>Cast</h2>
    <% @actors.each do |actor| %>
    <div class="actor">
      <%= image_tag actor.image %>
      <h3 class="actor-name"><%= actor.first_name %> <%= actor.last_name %></h3>
      <p class="actor-bio"><%= actor.bio %></p>
      <%= link_to "Read more", actor_path(actor) %>
    </div>
    <% end %>

  </div>
</div>